---
title: "0_host_species_representation"
author: "Raphael Eisenhofer"
format: 
  gfm:
    fig-width: 12
    fig-height: 7
    fig-dpi: 300
    toc: true
  html:
    fig-width: 12
    fig-height: 7
    fig-dpi: 300
    toc: true
editor: visual
---

## Representativeness of the different host metagenomes

```{r}
#| message: false
#| echo: false

library(tidyverse)
library(ggrepel)

df <- read_delim("../data/EHI_squamate_rodent_coassembly_info.txt")

n_hosts <- nrow(df)
n_squamata <- df %>% filter(host_order == "squamata") %>% nrow(.)
n_rodent <- n_hosts - n_squamata
```

We have `r n_hosts` different host taxa, `r n_squamata` are squamates, `r n_rodent` are rodents.

How well represented are the host orders by metagenomic data and number of MAGs?

```{r}
#| message: false

set.seed(1337)

df %>%
  ggplot(aes(x = host_order, y = n_mags, 
             colour = host_order, label = paste(host, n_samples))) +
  geom_jitter(height = 0, width = 0.1, alpha = 0.6, 
              aes(size = metagenomic_data_gbp)) + 
  geom_text_repel() + 
  theme_classic() +
  theme(axis.title = element_text(size = 16),
        axis.text = element_text(size = 14))
```
